---
HOSTS:
  debian8:
    platform: debian-8-amd64
    hypervisor: docker
    image: debian:8
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
  debian9:
    platform: debian-8-amd64
    hypervisor: docker
    image: debian:9
    docker_preserve_image: true
    docker_image_commands:
      # Provides /sbin/init
      - 'apt-get install -y systemd-sysv'
    docker_cmd: '["/sbin/init"]'
  ubuntu1604:
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
  ubuntu1804:
    platform: ubuntu-18.04-amd64
    hypervisor: docker
    image: ubuntu:18.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
  # NOTE: The 14.04 test uses images from ubuntu-upstart which layer on top of
  #       the official ubuntu images. The Upstart init system hasn't gotten any
  #       development to make it docker-compatible. Upstart needs some additional
  #       help in the form of a dummy service that executes `initctl emit` to
  #       simulate a normal boot sequence. These emitted events cause Upstart
  #       to execute items that are normally skipped when launched directly
  #       from `/sbin/init`. Such as signalling a runlevel so that `rc.d`
  #       scripts are executed.
  ubuntu1404:
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu-upstart:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'sudo update-rc.d ssh defaults'

CONFIG:
  # Beaker requirements are layered into the docker image at provision time.
  # Therefore, validating their presence is a waste of time and can cause hangs
  # during offline development.
  validate: false
