---
HOSTS:
  opensuse42:
    platform: sles-423-x86_64
    hypervisor: docker
    image: opensuse:42.3
    docker_preserve_image: true
    docker_cmd: '["/usr/lib/systemd/systemd"]'
    docker_image_commands:
      - 'systemctl enable sshd'

CONFIG:
  # Beaker requirements are layered into the docker image at provision time.
  # Therefore, validating their presence is a waste of time and can cause hangs
  # during offline development.
  validate: false
