---
language: ruby
sudo: false
cache: bundler
notifications:
  email: false
matrix:
  include:
    - rvm: 2.1.9
      bundler_args: '--without acceptance'
      script: 'bundle exec rake spec:unit'
    - rvm: 2.3.4
      bundler_args: '--without acceptance'
      script: 'bundle exec rake spec:unit'
    - rvm: jruby-9.1.5.0
      bundler_args: '--without acceptance'
      script: 'bundle exec rake spec:unit'
    - rvm: 2.3.4
      sudo: required
      services:
        - docker
      script: 'bundle exec rake spec:acceptance'
